[2024-09-25T06:07:13.627+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T06:07:13.898+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_articles_postgres_to_warehouse.extract_data scheduled__2024-06-18T14:00:00+00:00 [queued]>
[2024-09-25T06:07:14.003+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_articles_postgres_to_warehouse.extract_data scheduled__2024-06-18T14:00:00+00:00 [queued]>
[2024-09-25T06:07:14.008+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-25T06:07:14.343+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-06-18 14:00:00+00:00
[2024-09-25T06:07:14.612+0000] {standard_task_runner.py:72} INFO - Started process 305 to run task
[2024-09-25T06:07:15.142+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_articles_postgres_to_warehouse', 'extract_data', 'scheduled__2024-06-18T14:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_kum.py', '--cfg-path', '/tmp/tmpd1tgrst7']
[2024-09-25T06:07:15.386+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask extract_data
[2024-09-25T06:07:20.291+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_articles_postgres_to_warehouse.extract_data scheduled__2024-06-18T14:00:00+00:00 [running]> on host webserver
[2024-09-25T06:07:37.366+0000] {job.py:229} INFO - Heartbeat recovered after 16.85 seconds
[2024-09-25T06:07:40.225+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_articles_postgres_to_warehouse' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T14:00:00+00:00'
[2024-09-25T06:07:40.296+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T06:07:41.066+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/etl_kum.py", line 31, in extract_data
    src_conn = src_pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 146, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_source` isn't defined
[2024-09-25T06:07:41.415+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_articles_postgres_to_warehouse, task_id=extract_data, run_id=scheduled__2024-06-18T14:00:00+00:00, execution_date=20240618T140000, start_date=20240925T060713, end_date=20240925T060741
